# Generated by Django 3.1.7 on 2021-03-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание теста')),
                ('name', models.CharField(max_length=60, verbose_name='Название теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тэга')),
                ('quiz', models.ManyToManyField(related_name='tags', related_query_name='tag', to='testApp.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_question', models.CharField(choices=[('OA', 'one_answer'), ('SA', 'some_answers'), ('NI', 'number_input'), ('TI', 'text_input')], max_length=2)),
                ('explanation', models.TextField(verbose_name='Пояснение вопроса')),
                ('points_for_the_right_answer', models.PositiveSmallIntegerField(verbose_name='Баллы за правильный ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Корректность')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testApp.question')),
            ],
        ),
    ]
